version: '3'

services:
    app:
        build: .
        env_file:
            - .env            
        environment:
            - MONGODB_URL=value
        ports:
            - "2006:2006"
        depends_on:
            - mongodb
        volumes:
            - .:/src        
        networks:
            - node-network
    
    mongodb:
        image: mongo:6-jammy
        ports:
            - ${MONGODB_PORT}:27017
        volumes:
            - mongodata:/data/db
        networks:
            - node-network
        


networks:
    node-network:
        driver: bridge

volumes:
    mongodata:
        driver: local    